# Generated by Django 4.2.5 on 2023-11-04 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(choices=[('Mr.', 'Mister'), ('Mrs.', 'Mrs'), ('Miss.', 'Miss'), ('Dr.', 'Doctor'), ('Maj.', 'Major')], max_length=10)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('host', models.CharField(choices=[('ALEX', 'Alex'), ('SMITH', 'Smith'), ('JOHNSON', 'Johnson'), ('DOE', 'Doe'), ('WILLIAMS', 'Williams')], max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
